jwt:
  secret: mycomplexsecurepqssword

spring:
  application:
    name: e-maryam


  datasource:
    url: jdbc:mysql://localhost:3306/securemaryam
    username: root
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect:
          format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false
